sudo: required

services:
  - docker

before_install:
  - docker image build -t stozuka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker container run stozuka/react-test npm run test -- --coverage

after_success:
  - docker image build -t stozuka/multi-client ./client
  - docker image build -t stozuka/multi-nginx ./nginx
  - docker image build -t stozuka/multi-server ./server
  - docker image build -t stozuka/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push stozuka/multi-client
  - docker push stozuka/multi-nginx
  - docker push stozuka/multi-server
  - docker push stozuka/multi-worker

deploy:
  provider: elasticbeanstalk
  app: multi-docker
  region: ap-northeast-1
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-northeast-1-042882037923
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
